### ISSUE TITLE
Put archives directory location in a configuration file

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#113]
The default archives directory ("archives") is hardcoded into the code in a lot of places. This should be in a configuration file somewhere instead.

**Comment by npdoty** [comment]
I've created a command line option `--archives` for this, available in afb39be39d48a35d9bc993888f933d0a4c4356f3 and pr #281. (Tested with my w3c crawling, but it should work for other archives as well.)

**Comment by npdoty** [comment]
Do we need this added to `config.yml` as well? 

We've merged in #281 now, so we have the command line configuration present already. (I like to specify the archives directory location at the time that I'm issuing a crawl, as often different crawls will be used for different corpora.)

**Comment by sbenthall** [comment]
It looks like these are already in `config.yml`

I don't know if we've replaced the hardcoded links to the archives directory with a reference to the variables in config though.

The command line parameter/configuration option is definitely a great thing to have.
But having something that should be a configuration option hardcoded into the software is definitely a not great thing to have.

**Comment by sbenthall** [comment]
https://github.com/datactive/bigbang/blob/master/config/config.yml#L12

**Comment by npdoty** [comment]
Ah, no, I don't think we are using the `mail_path` parameter from `config.yml` as the default location for archives anywhere in the code. Functions in mail collection currently take an archive directory parameter, but choose `"../archives"` if no parameter is given. I agree that's not ideal behavior, especially since it returns a different value depending on the directory from which the executable is called. 

Let's fix this, but just fall back to the config variable when no explicit argument is provided.

**Comment by sbenthall** [comment]
Ok, some ramification of this issue has shown up in a lot of other debugging efforts. Time to take it on.

Here's what I think the behavior should be:

* There should still be a command line option and argument for picking the archives directory for these methods.
* The directory in the config.yml file should be used as a default
* The processing of the default archive directory should give a consistent result no matter where the script was executing from. The configuration may list a relative path, but it will be interpreted as relative to some fixed directory (like the top-level directory of the repository).

Does that sound right?

**Comment by sbenthall** [comment]
Linking in @davidberra who has ran into this issue a lot.

**Comment by davidberra** [comment]
ah ok i see this now, so i close the other issue and let's continue here

**Comment by davidberra** [comment]
i know how to read the parameter from config file, but i have no clue how to read the argument of collect_mail.py and how the two competing sources for the archive path should be dealt with :)

**Comment by sbenthall** [comment]
Looks like @Aryan-Barbarian got half-way through implementing this feature, but never wired it up. I'll pick up where he left off.

**Comment by sbenthall** [comment]
#309 has a fix for this. Though it's missing updates to all the notebooks.
