### ISSUE TITLE
Update setup.py with full requirements

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#173]
We need to update setup.py with the requirements from requirements.txt.

Can we make an automated test for this?

**Comment by npdoty** [comment]
`setup.py` also needs to have package metadata updated (description, author, url, version are all out of date, I think).

And per #356, I think it might also need to explicitly list the config module in the packages list. Or if we think this will be a frequently changing thing, we could maybe use [find_packages()](https://stackoverflow.com/a/14553799/108575).
