### ISSUE TITLE
Character set encodings not handled well in email parsing

### ISSUE THREAD

**Issue by dwins** [datactive/bigbang#186]
On my machine I get an error related to character encoding/decoding in running the example script from the README:

```
$ python bin/collect_mail.py -f examples/urls.txt
...
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 57: ordinal not in range(128)
```

I get other errors for other datasets but the script stops at the first error so this is a pretty inconvenient problem.

I would suggest that (a) while the parsed emails are in memory they should always be unicode objects, never str, and (b) the csv files that are generated should use utf8 encoding to ensure the widest possible character set coverage.

This may be an environment thing on my part, as I am using Python2.7 and I know that character set handling is one of the major changes for Python3.

**Comment by npdoty** [comment]
I believe this was fixed with #187.
