### ISSUE TITLE
extract email address from From field and pass downstream for processing

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#20]
Email addresses can be an important sign of institutional affiliation. This information should be preserved for future processing.

**Comment by npdoty** [comment]
This would also be useful for better entity resolution -- we probably want to split the name/description part of the From field from the email address. The address itself we'll use for some things (including institutional affiliation, maybe), and if the names match exactly, that could be a sign that this is the same person but using a different email address.

**Comment by sbenthall** [comment]
Fixed with this commit:

https://github.com/datactive/bigbang/commit/191c091f5031817dd814e14b2b1c75d3b3e3fad0
