### ISSUE TITLE
add Levenshtein in the requirement

### ISSUE THREAD

**Issue by emilienschultz** [datactive/bigbang#224]
I try to run Single Word Trend and I had an error no Levenshtein package
I fixed it with pip install python-levenshtein

**Comment by sbenthall** [comment]
were you using the conda or the virtualenv setup?

**Comment by emilienschultz** [comment]
I didn't use conda, I directly installed it with pip (I'm quite new in the
field, and a Software Carpentry guy told me : just report this bug, so I
did :) )

2015-07-08 21:37 GMT+02:00 Sebastian Benthall <notifications@github.com>:

**Comment by sbenthall** [comment]
Ok. Thanks so much for this ticket!

I have identified the problem. The setup.py file [1] does not include all of the Python dependencies [2]

[1] https://github.com/sbenthall/bigbang/blob/master/setup.py

[2] https://github.com/sbenthall/bigbang/blob/master/requirements.txt

This not a difficult thing to fix and I will be able to soon. Though if you would like to contribute a patch, a pull request for this would be welcome!

What would be ideal is if there were an automated test that can check for consistency between setup.py and requirements.txt

The dependencies change frequently and sometimes I forget to update them in the three places where they are recorded.

See here for more information about this issue:
https://caremad.io/2013/07/setup-vs-requirement/

**Comment by npdoty** [comment]
I've read that blog post more than once now and still don't really understand it at all.

When we add a new dependency, where are the places we need to update so that other users will know to install it? `requirements.txt` and `setup.py` and `conda-setup.sh` and `conda-requirements.txt`?

**Comment by sbenthall** [comment]
Yes. That's right. Though it's a bit ridiculous, isn't it?

See also #248
