### ISSUE TITLE
library git doesn't exist

### ISSUE THREAD

**Issue by emilienschultz** [datactive/bigbang#231]
repos_loader.py wants to import git, but I can't figure out how to install this library, and it's not in the requirements.txt

**Comment by Aryan-Barbarian** [comment]
This is the gitpython repository. In the `conda-setup.sh` file in the root directory, you'll find on line 7:

`pip install git+https://github.com/gitpython-developers/GitPython.git`

Running that file should work, but I will be debugging as they may have changed their module name.
