### ISSUE TITLE
License inhibits adoption

### ISSUE THREAD

**Issue by thewtex** [datactive/bigbang#234]
The viral nature of the GPL inhibits adoption by potential adopters / contributors because it is incompatible with more liberal licenses like MIT, BSD or Apache 2.

**Comment by sbenthall** [comment]
Thanks for commenting on this. It was certainly food for thought.

I've decided that for the sake of certain project goals, it is better to stick with the GPL license for now. I've written a statement about this here:

https://github.com/datactive/bigbang/wiki/Why-GPL-for-BigBang%3F

However, we are also transitioning control of the project into a community governance model. The license is subject to change at any time according to the determination of the community Steering Committee. If you would like to be on that steering committee, the best way to do that is to contribute to the code!

https://github.com/datactive/bigbang/wiki/Governance
