### ISSUE TITLE
Example Notebook Interaction Graph - Value Error

### ISSUE THREAD

**Issue by nllz** [datactive/bigbang#244]
After step:

```
plt.figure(230,figsize=(12.5, 7.5))
for i,arx in enumerate(archives):
    plt.subplot(230 + i) # create a subplot keyed to the index of this ml
    df = arx.data
    dff = filter_by_date(df,date_from,date_to)
    ig = graph.messages_to_interaction_graph(dff)
    print urls[i]
    print nx.degree_assortativity_coefficient(ig)
    draw_interaction_graph(ig)

plt.show()
```

I get the following output:```

---

ValueError                                Traceback (most recent call last)
<ipython-input-19-85373ec6d1e5> in <module>()
      1 plt.figure(230,figsize=(12.5, 7.5))
      2 for i,arx in enumerate(archives):
----> 3     plt.subplot(230 + i) # create a subplot keyed to the index of this ml
      4     df = arx.data
      5     dff = filter_by_date(df,date_from,date_to)

/usr/lib/python2.7/dist-packages/matplotlib/pyplot.pyc in subplot(_args, *_kwargs)
   1020 
   1021     fig = gcf()
-> 1022     a = fig.add_subplot(_args, *_kwargs)
   1023     bbox = a.bbox
   1024     byebye = []

/usr/lib/python2.7/dist-packages/matplotlib/figure.pyc in add_subplot(self, _args, *_kwargs)
   1003                     self._axstack.remove(ax)
   1004 
-> 1005             a = subplot_class_factory(projection_class)(self, _args, *_kwargs)
   1006 
   1007         self._axstack.add(key, a)

/usr/lib/python2.7/dist-packages/matplotlib/axes/_subplots.pyc in __init__(self, fig, _args, *_kwargs)
     62                     raise ValueError(
     63                         "num must be 1 <= num <= {maxn}, not {num}".format(
---> 64                             maxn=rows*cols, num=num))
     65                 self._subplotspec = GridSpec(rows, cols)[int(num) - 1]
     66                 # num - 1 for converting from MATLAB to python indexing

ValueError: num must be 1 <= num <= 6, not 0

<matplotlib.figure.Figure at 0x7f2f186b6210>

```
```

**Comment by sbenthall** [comment]
Specifically, this is the 'Show Interaction Graph' notebook

**Comment by npdoty** [comment]
@nllz can you verify whether this has been fixed in the current master branch? I think you're the only person who had seen this particular error. #297 was merged, which does fix some issues with missing dates, and that might resolve this issue. (#299 had the same fix, but we didn't merge it yet since it seemed duplicative.)

**Comment by nllz** [comment]
It works! tx @npdoty
