### ISSUE TITLE
BBIP 1: Using a Conda environment.yaml file as only supported installation option

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#248]
## BBIP 1: Using a Conda environment.yaml file as only supported installation option

Currently there are two methods of installation documented in the [README](https://github.com/datactive/bigbang/blob/master/README.md): an Anaconda based installation, and a `pip` installation. The Anaconda installation uses a [custom script](https://github.com/datactive/bigbang/blob/master/conda-setup.sh), which in turn uses uses a [list of conda requirements](https://github.com/sbenthall/bigbang/blob/master/conda-requirements.txt) and winds up making a lot of calls to `pip`. The `pip` installation just uses a standard pip [requirements.txt](https://github.com/sbenthall/bigbang/blob/master/requirements.txt) file.

There are a couple problems with this way of doing things.
- Because requirements need to be listed twice, for the conda installation and pip installation, it is harder to maintain the software as it evolves. There have been numerous instances of broken installations because some necessary package was not included in one of the installations.
- The custom conda installation script does not take advantage of the tooling Anaconda has around [environment configuration](http://conda.pydata.org/docs/using/envs.html#share-an-environment).

For this BBIP, which would be a major change in how installation is handled, I propose we replace the two installation methods with the simpler and better supported option of using _a conda environment file_, instead of a custom script.

It looks like conda environment files [do support listing pip dependencies](https://github.com/conda/conda-env#environment-file-example), for example when there isn't an available conda package.

While this does impose an additional burden on users who have not yet installed the Anaconda distribution, sticking to this install path will make installations across the board more consistent and easier to support.

See also: 

http://stackoverflow.com/questions/35245401/combining-conda-environment-yml-with-pip-requrements-txt

**Comment by nllz** [comment]
+1

**Comment by npdoty** [comment]
I'm not sure I yet understand all the implications of this change. All users will need to install Anaconda and dependent packages will need to be handled by the `conda` tool, which uses `environment.yaml` (rather than `requirements.txt`), but can also accommodate pip-only packages?

I've been happy using pip, but I'm fine switching to Anaconda if it'll make installation/setup easier for new users.

**Comment by sbenthall** [comment]
You are quite right, @npdoty 

I realize now that with this BBIP I muddled two issues that would be better dealt with distinctly.

The first issue is replacing the custom conda install script with the conda `environment.yaml`. I will make a pull request for _just this change_.

The second issue is whether or not we should deprecate the `pip` installation instructions. If you are happily using `pip` and would prefer to continue to use it, that's a reason to hold off on this second change until we have at least had the chance to compare the two installation paths.

**Comment by npdoty** [comment]
Although I've been happily using `pip`, I would support this change if it would make it more straightforward when we add new requirements (i.e. making a change in 2 places instead of 4). @sbenthall above you said you were going to make a PR on using environment.yaml. I think we should probably resolve that before switching installation further.

**Comment by sbenthall** [comment]
Yes, I apparently have been on the hook for this for almost a year.
I'll get to this soon.

**Comment by sbenthall** [comment]
Closing this now.

The problem is that Conda's environment.yaml files do not work cross-platform.
