### ISSUE TITLE
MHonArc archive import

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#257]
Allow for collect_mail from [MHonArc](https://www.mhonarc.org/) web mailing list archives.

Example list: [nettime](https://nettime.org/Lists-Archives/)

**Comment by npdoty** [comment]
I see some of these in IETF mailing list archives as well. (Some of those lists have full .mbox downloads available at another location, but I'm not sure all do.)

**Comment by sbenthall** [comment]
too obscure
