### ISSUE TITLE
fix documentation and website to reflect new project URL and email lists

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#264]

**Comment by npdoty** [comment]
The website should also recognize new governance (DATACTIVE, bylaws, etc.) and wider participation.

**Comment by nllz** [comment]
updated most links, governance stuff should still be added

**Comment by sbenthall** [comment]
Fixed remaining website links.

README still needs to be changed to address original ticket scope.

@npdoty I agree that recognition of the new governance would be good. I'm not entirely comfortable with the current language on the site because it doesn't recognize e.g. your contributions.

But the current website is a variation on something simply auto-generated by GitHub.
https://pages.github.com/

I think we can get by without a major website overhaul for 0.2. @davidberra may want to weigh in as to whether he has the time/energy to do more with the website before the next release.

**Comment by sbenthall** [comment]
To be clear, I think that when the governance stuff is added it will all be great. I just care a lot about having all contributors and contributing organizations recognized. :)

**Comment by sbenthall** [comment]
New mailing list now corrected in README:

https://github.com/datactive/bigbang/commit/a5227a511d0220c29c5d89c3af86eef51b0787c5

see also ticket #266

**Comment by sbenthall** [comment]
See also #115 

GitHub provides a significant amount of tooling around project websites. We should evaluate the options and choose how we would like to proceed in a way that anticipates extensibility in the future.

**Comment by sbenthall** [comment]
Closing as duplicate of #286
