### ISSUE TITLE
Gardening the examples notebooks

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#271]
Look over the notebooks and decide what to keep, what to remove, what to clean up, and what to move to core.

**Comment by npdoty** [comment]
We might also want to improve documentation/segmentation, to clarify which notebooks are polished/good-to-go vs. experimental. (Maybe different subdirectories? Or a wiki page that explains the order?)

**Comment by npdoty** [comment]
@nllz thinks we put the good to go ones in the examples directory, and the others in an experimental subdirectory

**Comment by sbenthall** [comment]
As I look through the notebooks now, I think there are some I would prefer to keep in the main examples directory, and others I would happily push to the experimental directory.

I'd be happy to take a shot at gardening once #317 is pulled.

**Comment by nllz** [comment]
Gardening happened, so I hope we can pull some things now; https://github.com/datactive/bigbang/pull/324

**Comment by sbenthall** [comment]
Thanks for the excellent work, @nllz
