### ISSUE TITLE
Documentation of current capabilities

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#286]
Improve documentation before the next release.

**Comment by npdoty** [comment]
I think maybe the README.md file could be split up into other documentation pages; right now it has a lot of detail about Git data collection that I'm not sure every casual user needs to read right off the bat.

And we'd want to update the gh-pages branch to include a description of the next release and the current set of functionality.

**Comment by npdoty** [comment]
- [ ] add Gitter.im badge to the README
- [ ] move Git data collection to separate wiki page

**Comment by npdoty** [comment]
- [ ] fix installation instructions in README to refer to main repository

**Comment by sbenthall** [comment]
#329 is for the website / gh-pages update. Otherwise, this ticket is complete. Thanks @npdoty for the excellent work.
