### ISSUE TITLE
Collecting lists of lists

### ISSUE THREAD

**Issue by npdoty** [datactive/bigbang#287]
I think we have a few files, in different directories/branches/repositories that include potentially useful lists of mailing list archives or related git repositories that correspond to a particular organization. Would it make sense to make a `data` directory or similar to hold these in a slightly more organized fashion?

In particular, `examples` contains:

    cfa_urls.txt
    codeforamerica_urls.txt
    dlab-berkeley_urls.txt
    edX_urls.txt
    git_urls.txt
    glass-bead-labs_urls.txt
    mm.icann.org.txt
    mm.ietf.org.txt

And I'm now working on https://github.com/npdoty/bigbang/blob/gender-2/w3c-demographics/w3c-groups/w3c-current-lists.txt (and similar ones for IETF).

We've discussed having entirely separate repositories for large datasets, and the .txt file list of lists should probably be one part of those, but would it also be useful in general to have a directory with lists of lists of interest?

**Comment by npdoty** [comment]
Also, as noted in #278, I guess there is a default list of URLs that's used for teaching/demonstration examples.

**Comment by sbenthall** [comment]
I like the idea of a description of the files.

Another possibility would be to use a markup language for these files, and given them a bit more structure.

That way, the files containing lists of URLs could have documentation included in them. A description of the projects, maybe other things that come up.

**Comment by npdoty** [comment]
We could potentially have lots of additional descriptive data that would justify a separate markup format, but I feel like we should stay simpler while we can.

Perhaps a starting point would be to have #-preceded comments at the top of these .txt files that would be ignored by consumers. Then you could just explain, for example:
`# this is a list of all mailing lists for active IETF working groups`

**Comment by sbenthall** [comment]
I'm fine with that change.
I imagine it would not be hard to write something that ignores those lines into the parser.

I would like to flag that if we start writing a custom parser for these files that is much more complicated than just that, I would prefer we use something well-established than create a lot of custom code that we then have to maintain by ourselves.

**Comment by nllz** [comment]
I was hoping we could indeed simply write descriptions in Markdown (or uncomment lists that are not working), but collect_mail.py -f currently cannot deal with that. So will we either alter collect_mail.py -f or create a markdown file in the directory with a short description? I can start with the latter.

**Comment by sbenthall** [comment]
Having a Markdown file with description of the lists sounds like a good incremental step to me.
We could scope this ticket as that.

I've made ticket #328 for further tracking of the list-of-list comment markup issue.

**Comment by sbenthall** [comment]
Did #334 solve this ticket? I don't think it did. urls.txt is now handled better.

But what about lists of .txt files? Does this still need work?

**Comment by nllz** [comment]
https://github.com/datactive/bigbang/pull/336 hopefully solves this

**Comment by sbenthall** [comment]
Closed with #336
