### ISSUE TITLE
Update all notebooks to Jupyter v4 or higher

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#294]
Some of the notebooks are in an older version of the jupyter format.
These predate that shift from ipython notebook into Jupyter.
It would be best if all the notebooks were updated to the new format, which is now quite old and robust.

**Comment by nllz** [comment]
What is still needed for this?

**Comment by sbenthall** [comment]
An up-to-date version of Jupyter will complain when it opens a notebook of an earlier (< 4) format version and offer to convert it.

We need to run this conversion on any notebooks that we haven't already and commit the change.

Each notebook has a metadata field, "nbformat", which has the version number of the notebook. You can find this line easily with a `grep` command.

When the version is correct, this line will read:

`"nbformat": 4,`

When it is incorrect, it will read:

`"nbformat": 3,`

So checking this condition is a good way to make sure you haven't missed one. But note that just changing the number will not change the notebook version, since it's a deeper change to the underlying JSON schema.

**Comment by nllz** [comment]
@davidberra is gonna make this happen :)

**Comment by davidberra** [comment]
check the notebooks with grep and all of them have 'nbformat' set to 4. guess this means the issue is closed?

**Comment by sbenthall** [comment]
+1
