### ISSUE TITLE
collect_mail.py No module named bigbang.repo_loader 

### ISSUE THREAD

**Issue by davidberra** [datactive/bigbang#300]
when running the script 'collect_mail' for single url (-u) it gives this error

No module named bigbang.repo_loader

**Comment by sbenthall** [comment]
What was the precise command?
We're you using Python 2 or 3?

**Comment by davidberra** [comment]
ok, i copypasted the wrong line and ran 'collect_git' instead : P

however, now it gives 'no module named bigbang.mailman'

**Comment by sbenthall** [comment]
I think you may be running Python 3.

Try running with `python2 bin/collect_mail.py ...`

**Comment by davidberra** [comment]
Nope, same issue. And i think im on python2.7

**Comment by sbenthall** [comment]
Have you created and activated the conda or virtual environment?

**Comment by davidberra** [comment]
pam pam pam. issue closed : )
