### ISSUE TITLE
path to /archives  

### ISSUE THREAD

**Issue by davidberra** [datactive/bigbang#305]
when correctly running collect_mail.py and successfully creating an archive, it prints this at the end of data collection (very confusing!)

unzipping 0 archive files
Opening 0 archive files
'No messages in ../archives under ietf. Did you run the collect_mail.py script?'

try to look into mailman.py; the message is printed when the length of 'arch' is zero. the files are really there though

**Comment by davidberra** [comment]
so apparently in mailman.py the directory with the data is referred to as ../archives/ietf-privacy (for example). is I use this relative path it find no files! if i use the absolute path (in my case /home/berra/bigbang/archives/ietf-privacy), it does. 

isn't ../ the correct way to point to parent directory!?

**Comment by davidberra** [comment]
and yeah, considering that now the location of archives is arbitrary, we should find a way to have that parameter accessible also in this module

**Comment by sbenthall** [comment]
Great points. This issue is related to #113 

Can you elaborate on what you mean by "we should find a way to have that parameter accessible also in this module"? In which module? What sort of functionality would be ideal, in your view?

**Comment by davidberra** [comment]
am talking about mailman.py; here the archive folder is referenced as ../archives (which should mean: go from bigbamg/bigbang to bigbang/archives...although it doesnt seem to work for me, see the comment above). however now collect_mail.py takes the archives path as a parameter...so there is a contradiction between the two. if we want to keep the archives path as a parameter, we have to find a way to access the path passed as an argument to collect_mail.py in mailman.py
frankly not sure how that can be done : )

otherwise we could keep archive as a fixed path; but still there is this weird issue i have that with relative path (../archives) i cannot access the donwloaded files, while with absolute path (/home/berra/bigbang/archives/) i can

**Comment by davidberra** [comment]
btw currently working on this issue because i cant load any file so far so cant go on testing notebooks!

**Comment by davidberra** [comment]
ah, maybe i got why i have that behaviour. the reference directory (from which relative paths are calculated) is the one where you launch the script, not the one where the relevant module (mailman, in this case) is located?

**Comment by davidberra** [comment]
ok i solved by switching from ../archives to archives, as the reference directory is /bigbang, not /bigbang/bigbang.

I keep the issue open because there is still the conflict with the collect_mail that takes a free argument for the archives directory
