### ISSUE TITLE
code of conduct

### ISSUE THREAD

**Issue by npdoty** [datactive/bigbang#321]
Should have a code of conduct, to make a public commitment and welcome new contributors.

- [x] setup separate mailing list (not publicly archived, includes core developers as recipients)
- [x] update the README
- [x] update the Governance wiki page

**Comment by npdoty** [comment]
We can start with this one, as suggested by GitHub:
https://www.contributor-covenant.org/version/1/4/code-of-conduct.html

**Comment by npdoty** [comment]
@sbenthall @Aryan-Barbarian I plan to update the Governance wiki page to note that:

> All members of the community are expected to abide by and maintain the [code of conduct](#) in order to make participation in our project and our community a harassment-free experience for everyone.

Let me know if there are any objections / different language for that more formal page.

**Comment by sbenthall** [comment]
This is good, IMO. Thanks, Nick.

**Comment by sbenthall** [comment]
See the recent dev list discussion about some (small!) discrepancies between the roles defined in the Code of Conduct and the roles defined in the Governance document.

I don't think this is anything that should block the adoption of the code of conduct, but getting clarity on how those two documents interact would be a nice addition to the governance process.

For example: in the Governance document, we could note that contributors need to sign off on the pledge, perhaps by committing their names to the end of the code of conduct document in version control.

**Comment by npdoty** [comment]
updated the Governance page with that link. I agree we could clarify or update the exact roles at some point too.

I'm not sure we need contributors to sign/update the pledge, as it's an expectation for everyone even before they're formal committers.

**Comment by sbenthall** [comment]
Hmm. I kind of like that idea though...I'd like to open it up for more discussion. I'll make a new issue
