### ISSUE TITLE
test coverage for mailman.py

### ISSUE THREAD

**Issue by npdoty** [datactive/bigbang#343]
Initial coverage is only 32%, according to https://gist.github.com/sbenthall/05f585518cac8e27039a7c1b5da11a62

**Comment by npdoty** [comment]
I started this in https://github.com/npdoty/bigbang/commit/98b0a77c88c7527a16db9c9bc8bfd90a503f356d, covering the `normalize`, `get_list_name` and `open_activity_summary` methods.

**Comment by npdoty** [comment]
Opened pr #350 with my new tests, though this submodule isn't complete (it's about 50%)

**Comment by npdoty** [comment]
Coverage for `get_text` and `collect_archive_from_url` needed to catch the decoding issues in the Py3 conversion.

**Comment by Christovis** [comment]
Currently we have:
archive.py                63.87%
entity_resolution.py  83.05%
git_repo.py               69.37%
listserv.py                 80.32%
mailman.py              48.03%
parse.py                   56.10%
process.py               44.70%
repo_loader.py         47.44%
thread.py                 68.67%
utils.py                     53.57%
w3crawl.py               91.20%

Can this issue be closed?

**Comment by npdoty** [comment]
I don't feel strongly about how we track test coverage of different modules: we can have different issues for different files, which I think is how we started, or just have regular work items on reviewing coverage and filling in gaps. 

But it looks like `mailman.py` is still substantially below the 60% coverage goal.

**Comment by Christovis** [comment]
With PR #471 the code coverage of mailman.py is improved to 62.63%.
