### ISSUE TITLE
replace print statements with logging

### ISSUE THREAD

**Issue by npdoty** [datactive/bigbang#353]
Rather than having random print statements in various modules for informal debugging, it would be nice to adopt use of a logging library, and separate the statements into debug, info, warning and error levels. 

`mailman.py` seems like the worst offender, and it makes the stdout very difficult to work with in scripts and notebooks.

If we had a common convention, it would also be good to document it so that newly written code can use the same basic standard.

**Comment by Christovis** [comment]
Could you maybe make a PR for `mailman.py` with a suggested standard which we can then adopt in other places too?

**Comment by Christovis** [comment]
With PR #546 this issue is solved
