### ISSUE TITLE
MostUsedWordsPerAllUsers returns an empty CSV

### ISSUE THREAD

**Issue by Nasiff** [datactive/bigbang#359]
I was doing some word analysis using BigBang and the jupyter notebook MostUsedWordsPerAllUsers notebook (located in /examples/word_analysis) simply returns an empty CSV file when the code is executed.
The same notebook gives a NameError which I referenced in this pull request #358

**Comment by npdoty** [comment]
@davidberra @nllz could you look at this issue? I think you've worked on this notebook more recently.

**Comment by sbenthall** [comment]
Testing out your pull request, #358 (thanks for it) I noted the default mailing list isn't one that ships with the repository.

To replicate your error...can you tell me a public mailing list for which you get this error?

**Comment by davidberra** [comment]
So i just tested this on few mailinglists, including "hrpc" (this is the one you are wokring on, right?), and works fine for me. Weird

Some checks:

Is the variable "n_top_words" maybe set to 0 for some reasons? 
Does the block before ("extract list of users...") take quite some time to compute or is it immediate?
Maybe try to check if the dictionary is empty with print len(user_wordcount.keys())

**Comment by Nasiff** [comment]
> Is the variable "n_top_words" maybe set to 0 for some reasons?

Nope, I kept that at its default (n_top_words = 10)

> Does the block before ("extract list of users...") take quite some time to compute or is it immediate?

The block takes a second (0.94s to be exact). which makes sense because the dictionary is actually empty after I tried printing out the length of the user_wordcount dictionary. More details below:
![image](https://user-images.githubusercontent.com/29618544/52376247-8c77c600-2a2f-11e9-85d2-56efca66249b.png)

I made the script from scratch again just so I can start anew. It still gives me an empty CSV file (which makes sense as the dictionary is empty). I copied it exactly like the way it was on the Jupyter notebook and I still get the same CSV file.

The only parts of the script I changed are the highlighted portions marked below (I was just trying to point it towards the HRPC CSV file that sits in the **_archives_** folder)
![image](https://user-images.githubusercontent.com/29618544/52376399-0f008580-2a30-11e9-913c-c348c8830499.png)

**Comment by davidberra** [comment]
ummm can you check if the archive is being really loaded?

print len(archives_data) or len(archives), at the end of the second block

**Comment by Nasiff** [comment]
> ummm can you check if the archive is being really loaded?

Yes, all the emails actually do seem to get loaded.

![image](https://user-images.githubusercontent.com/29618544/52522178-a4c62b80-2c4f-11e9-8fa7-f70181597615.png)

**Comment by Nasiff** [comment]
I have just created a Pastebin for the entire script which you can check out here:
https://pastebin.com/WgbUwRCm

**Comment by npdoty** [comment]
Since you have data (that 2197 count), and it takes a little time to run through the list of users, it seems like maybe something is happening in this block:

```
for user in set(users):
    try:
        messages = archives_data[archives_data["From"] == user]["Body"]
        user_wordcount[user]= count_words(messages)
    except: pass
```
That `except: pass` may be silently capturing some error, so you might remove the try-except and see if any exceptions are being thrown. That might give you something more direct to troubleshoot.

One debugging advantage of using the Jupyter notebook rather than a standalone script is that you can inspect the data at different steps. If you just execute `archives_data` (which should be a Pandas dataframe) you can get a little table output and see if it has the columns that you're expecting or not.

**Comment by Nasiff** [comment]
Excellent!
So removing the try/except clause helped me clean out most of the errors I had (in terms of not having the right libraries) and that lead me to fix the script successfully!
Thanks, @npdoty and the others for helping me fix this error.

**Comment by npdoty** [comment]
Glad to hear it. We should probably avoid `except: pass` in general, as it's likely to create this kind of troubleshooting confusion. If we don't want a script to stop on an exception (very reasonable, given the messy data we often work with), then using error logging would make the problems visible.

**Comment by Nasiff** [comment]
I agree. If the script actually threw an error we wouldn't have to go through the whole process of finding which part of the code was responsible for the unwanted end result.
