### ISSUE TITLE
Many example notebooks have errors in code execution checked in

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#364]
The `examples/` directory is a showcase of our functionality.

Several of the notebooks in that directory have code errors checked in, which is bad.

Code note executed:
https://github.com/datactive/bigbang/blob/master/examples/experimental_notebooks/Person-Group%20Bipartite%20Graph.ipynb

Code error:
https://github.com/datactive/bigbang/blob/master/examples/experimental_notebooks/Cohort%20Visualization.ipynb

Code error:
https://github.com/datactive/bigbang/blob/master/examples/word_analysis/CheckWordsTrendsOverTime.ipynb

Assigning to Niels, the Notebook Gardener. Can you make these flowers bloom?

**Comment by nllz** [comment]
Will go through the the example notebooks, not the experimental ones though, right?

Good moment for me because I started analyzing RIPE mailinglists.

**Comment by sbenthall** [comment]
We can make automated tests for the notebooks!

Let's do this before 1.0
