### ISSUE TITLE
Package and include ietf draft data resource

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#370]
https://github.com/npdoty/rfc-analysis

**Comment by npdoty** [comment]
Do we want `rfc-analysis` to be a separate module (that can be installed via PyPI or wherever) and then included as a dependency? Or do we just want to include this standards document analysis directly in BigBang?

I'm open to either (and as a sole contributor, I think there shouldn't be any licensing issues), but if there's notes/preferences from past calls or others, I'd be interested to hear them.

**Comment by sbenthall** [comment]
I've started working with the glasgow-IPL data tracker:
https://github.com/glasgow-ipl/ietfdata

My sense is that it has a much more complete record of data available to it, and Colin has been very response to new issues.

It is also already packaged on PyPI
https://pypi.org/project/ietfdata/

I think it's probably best if we use this instead of RFC-analysis

**Comment by npdoty** [comment]
Yeah, I think that ietfdata package is great, and definitely further developed than my rfc-analysis scripts. 

I think rfc-analysis might include slightly different functionality (word analysis and section lengths), but it would be easy enough to copy over that code or just use it in branches that need it.

**Comment by sbenthall** [comment]
#386

**Comment by npdoty** [comment]
@sbenthall are we fine to close this now that #386 is merged?

**Comment by sbenthall** [comment]
yep!
