### ISSUE TITLE
import ietfdata

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#375]
This python package exposes the IETF data tracker, with a lot of good information in it:

https://pypi.org/project/ietfdata/
https://github.com/glasgow-ipl/ietfdata/tree/master/ietfdata

We can add it as a dependency and then include a notebook showing how, for example, to plot IETF working group email frequency with IETF working group RFC frequency.

**Comment by npdoty** [comment]
This was merged in June, but we are now hearing reports about a blocking issue when installing `ietfdata`.

**Comment by npdoty** [comment]
There may be some missing dependencies for `ietfdata`. So far, I had to `pip install` the `pavlova` package, which does parsing into dataclasses.

**Comment by lumisota** [comment]
Investigating this as glasgow-ipl/ietfdata#103.

**Comment by lumisota** [comment]
This should now be fixed in the latest released (`ietfdata 0.4.0`).

**Comment by sbenthall** [comment]
Thank you @lumisota !
