### ISSUE TITLE
list publications or outputs using BigBang

### ISSUE THREAD

**Issue by npdoty** [datactive/bigbang#376]
@nllz noted that he has a couple papers with results from BigBang. It would be nice to include a list of publications/reports/presentations that have used BigBang (even if it won't be easy to keep an exhaustive list).

That list could be included in the gh-pages branch (and available on the project page here: http://datactive.github.io/bigbang/), with maybe just a link from the README.

**Comment by sbenthall** [comment]
+1 this is a good idea.

In general the website is woefully out of date and could use a revamp
http://datactive.github.io/bigbang/

**Comment by nllz** [comment]
There is a PR for that :) 

https://github.com/datactive/bigbang/pull/389

**Comment by nllz** [comment]
Hmmmm - I messed up the website, so I recreated it from scratch, but now in markdown, probably easier editing. It's still not pretty, but it might be a bit better. https://datactive.github.io/bigbang/

**Comment by nllz** [comment]
(ah, and I added the publications)
