### ISSUE TITLE
60% test coverage

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#38]
Automated testing is important. Do not close the 0.1 milestone without 60% automated test coverage of code.

**Comment by sbenthall** [comment]
This old ticket still asked for more test coverage.

Luckily, we already have 45% test coverage; just 15% more to go!

https://gist.github.com/sbenthall/05f585518cac8e27039a7c1b5da11a62

**Comment by npdoty** [comment]
See #342 and #343 for the scripts that are most dramatically missing test coverage.

**Comment by npdoty** [comment]
running with `--cover-inclusive` reminds us that we also need to test these:

```
bigbang/get_dependencies.py        8      1    88%
bigbang/graph.py                  97     82    15%
bigbang/plot.py                   33     27    18%
bigbang/twopeople.py              51     34    33%
```

(Or some of these files we could remove from the core library.)

**Comment by npdoty** [comment]
Currently we don't have any tests for scripts in the `bin/` subdirectory. Most significant in there is `collect_mail.py` but I've also been adding more for creating activity frames and calculating tenure across lists.
