### ISSUE TITLE
attendance data scripts not working right...

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#392]
I'm not sure why I haven't seen this before, but the attendance data script is running very slow and then choking.

The error it gives is connected to concatenating dataframes when at least one has duplicate columns.

Looking into this, the dataframes generated by parsing some of the old attendance pages have *thousands* of columns, which is not right. 

It looks like one reason for this may be malformed HTML. The table rows do not have closing tags `</TR>`.

view-source:https://www.ietf.org/registration/ietf94/attendance.py

I do believe this was working before so it may be due to a change in the attendance.py script generating those web pages.

**Comment by sbenthall** [comment]
The error: https://stackoverflow.com/questions/26226343/pandas-concat-yields-valueerror-plan-shapes-are-not-aligned

**Comment by sbenthall** [comment]
Should we deprecate the attendence scrapers in favor of using the datatracker information?

**Comment by npdoty** [comment]
Yeah, I think so. I will put together a PR with a notebook that uses the datatracker for attendance (so that we know it's possible and how to use it) and removes the attendance page scraper.
