### ISSUE TITLE
collect metadata for all submissions with working group draft scraper

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#397]
From @csperkins

> dt = DataTracker(cache_dir=Path("cache"))
> 
> g  = dt.group_from_acronym("httpbis")
> for d in dt.documents(group=g, doctype=dt.document_type_from_slug("draft")):
>     print("")
>     for sub_url in d.submissions:
>         sub = dt.submission(sub_url)
>         print(F"{sub.document_date.strftime('%Y-%m-%d')} {sub.name}-{sub.rev}")
>         for a in sub.parse_authors():
>             print(F"           {a['name']} <{a['email']}>")

**Comment by sbenthall** [comment]
fixed now in #394

**Comment by npdoty** [comment]
should this issue be closed? or can the particular desired feature be detailed more?

**Comment by sbenthall** [comment]
can be closed!
