### ISSUE TITLE
Ambiguity of 'url' in mailman..open_list_archives()

### ISSUE THREAD

**Issue by Christovis** [datactive/bigbang#399]
Issue:
In the notebook `/master/examples/name-and-gender/Analyze Senders - Name and Gender.ipynb` at `In [12]` the archives are loaded as:
```
urls = ["http://www.ietf.org/mail-archive/text/ietf-privacy/",
        "http://lists.w3.org/Archives/Public/public-privacy/"]
mlists = [(url, mailman.open_list_archives(url,"../../archives")) for url in urls]
```
This fails, as in 'url' in this case has to be the name of the sub-directory of 'archive_dir', while at other times it is a proper URL. Something must have changed in between 8 and 4 months ago, as newer notebooks use a sub-directory name instead a URL (e.g. as done in `/master/examples/experimental_notebooks/IETF Participants.ipynb`)

Error message:
`MissingDataException: 'No messages in ../../archives under ietf-privacy. Did you run the collect_mail.py script?'`

Solution:
First use download the data via, e.g. `python bin/collect_mail.py -u http://lists.w3.org/Archives/Public/public-privacy/`

Improvement:
I will create a PR with a suggestion to use either the url as a proper URL and invoke `mailman.collect_from_url()`, or 'archive_dir' to give the complete path to the data (e.g. archives/public-privacy/). The current idea is [here](https://github.com/Christovis/bigbang/blob/2d7eec14b291f1f7c208f3af05cd84dfc8439f19/bigbang/mailman.py#L354)

**Comment by sbenthall** [comment]
closed with #400
