### ISSUE TITLE
Setting up pre-commit routine to ensure coherent python formatting

### ISSUE THREAD

**Issue by Christovis** [datactive/bigbang#401]
I would like to make a suggestion regarding the code format. Reading and reviewing code can be made easier if the merged code has same formatting as the master branch (as outlined in, e.g., [here](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/)).

What do you think about it?

If you like the idea, I will create a PR.

**Comment by sbenthall** [comment]
I'm in favor of this!

**Comment by npdoty** [comment]
👍 
Also, if we just documented what style guidelines we *should* follow (is it just PEP8?), what it applies to and what tool to run on our machines before committing, I could do that when I'm developing and before I commit. We should probably have that in the README in any case.

**Comment by Christovis** [comment]
I have created the [PR](https://github.com/datactive/bigbang/pull/403). Have a look and see if you like it.

Yes having some style guidelines in the README is really helpful (at the minimum for code and doc-strings).

**Comment by Christovis** [comment]
This enhancement was implemented wit #403 and #408 .
