### ISSUE TITLE
environment errors

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#402]
Trying a fresh install, I'm running into several errors:

- Need to manually install `GitPython`, `nbformat`, `nbconvert`, and `validator_collection`

Then getting this error, which looks like a Pandas versioning issue:

```
self = <bigbang.git_repo.GitRepo object at 0x7fc795f9b358>
attribs = ['HEXSHA', 'Committer Name', 'Committer Email', 'Commit Message', 'Time', 'Parent Commit', ...]

    def populate_data(self, attribs = ALL_ATTRIBUTES):
        """Populate data."""
        raw = dict()
        for attrib in attribs:
            raw[attrib] = list();
        repo = self.repo
        self.gen_data(repo, raw);
        print((type(raw["Time"])))
    
        # TODO: NEEDS TIME
>       time_index = pd.DatetimeIndex(raw["Time"], periods = 24)
E       TypeError: __new__() got an unexpected keyword argument 'periods'

bigbang/git_repo.py:122: TypeError
```

**Comment by Christovis** [comment]
Is there any reason for why the environments setup are so different for conda and pip?

Did your above mentioned error occur after a pip installation?

**Comment by sbenthall** [comment]
The reason for different pip and conda setups are that while in theory conda makes it easier to build an environment with scientific libraries, they don't host all the libraries we need. So the conda setup installs what can be installed via conda, and uses pip for the rest.

https://github.com/datactive/bigbang/blob/master/conda-setup.sh

That design was implemented several years ago and both conda and python package management systems are constantly changing. So it's possible this needs a maintenance review.

But also, I've been having local Python environment issues lately due to some messy upgrades. So I will need to revisit this ticket and see if I can reproduce my own error here.

**Comment by Christovis** [comment]
hmmm, maybe it would be worth looking into Docker?

**Comment by sbenthall** [comment]
I personally wouldn't want to do development in a Docker container.
I guess mileage can vary on that.
So far there are no "production deployments" of BigBang but that would be cool if there was a good use case.
