### ISSUE TITLE
Create video tutorials (relavance, pre-install, install, use, integrated)

### ISSUE THREAD

**Issue by nllz** [datactive/bigbang#420]

**Comment by nllz** [comment]
script part 1 and 2

- Introduction to BigBang
    - What is a mailinglist?
        - A way to be in conversation with a group of people by using asynchornous technology that works on low-bandwith Internet connections
        - Used for software projects as well as Internet governance
    - Why is it important?
        - One function of mailinglists is that archives are kept
        - Not just an archive for archive's sake, but also to document decisionmaking. Because of the important of software and Internet infrastructure, these documents could be seen as public policy documents, and analyzed as such
        - When these archives are publicly accessibl
    - Where is it used?
        - Mailinglists have been around since the late 1960. There are two main software packages to administer mailinglists: Mailman and Listserv. These are the ones that can be analyzed with BigBang. 
        - There are also other mailinglists such as Google Groups - but these are not supported by BigBang, in part because Google makes it very hard to access them. 
    - What can BigBang do with mailinglists?
        - BigBang can do many things, but it has three basic functionalities: basic statistics, network analysis, and discourse analysis
        - Statistics
            - Counting people that post to a mailinglist (over time)
            - Counting ppls tenure
            - Counting emails (total + list)
            - Counting threads, longest thread
        - Network analysis
            - Affiliation of actors
            - Centrality
            - How networks form within a list and between list
            - Explore modularity and fragmentation in communities
        - Discourse analysis
            - Word trends over time
            - Key word occurence
            - Most used word per person or per all users
            - Special word analysis
- How to install BigBang
    - on Ubuntu
        - it's easy on linux
        - If you run Mac, the instructions are very similar, check the BigBang website
        - If you run Mac or Windows you can always choose to either run Ubuntu in a virtual Machine, or with a persistent live USB. Especially if you're not very comfortable with the command line yet, this is a safe way to experiment and not mess up your production environment.
            - Instructions on setting up a virtualbox or use the LiveUSB (and make it persistent)
                - https://www.linuxuprising.com/2019/08/rufus-creating-persistent-storage-live.html
        - Installing goes through a couple of steps. I will not just go through the steps, but also seek to explain them. If you're just looking for the commands, look at the website.
        - 1. Install Anaconda 
            - Anaconda is a virtual environment on your systems that keeps track of which versions of files you're using. Software is pretty much always built on other software, but if that software changes, it might break something. This is why it is important to try to keep the versions consistent. This is what Anaconda does for is. So let's go the the anaconda website, download the package and install it.
            - Then add Anaconda to path - do this else the conda and source activate commands will not work!
        - 2. Install git
            - Git is a version management control sytems. It is the interface with the systems where we develop BigBang. You need this in order to download BigBang.
                - Now open a terminal and first type:
                    - sudo apt install git
                    - then download bigbang:
                        - git clone https://github.com/datactive/bigbang.git
        - 3. Install BigBang
            - Now we will need to install all the software needed for BigBang to run and setup an environment in which BigBang will run. For this we will run an install script
                - type: bash conda-setup.sh 
        - Congrats - you have now installed BigBang
        - If there are any issues with this installation process - feel free to send an email to the BigBang mailinglist: bigbang-user@data-activism.net
        - 
- How to use BigBang
    - Get data
    - What question do you want to ask?
    - Start a Jupyter notebook
    - edit the notebooks variables
    - Play
    - see data, export data, use data (also with Gephy etc)
-

**Comment by npdoty** [comment]
is this finished, @nllz ? Or is some part of it finished in the linked video from the current README?

**Comment by nllz** [comment]
Sorry about that - indeed finished it with https://www.youtube.com/watch?v=JWimku8JVqE
