### ISSUE TITLE
IETF attendance updates for online-only meetings

### ISSUE THREAD

**Issue by npdoty** [datactive/bigbang#424]
IETF 108, 109, 110 (and maybe some to come) have been all virtual and use a different web page format for showing attendance, e.g. https://registration.ietf.org/108/participants/remote/

We should update `ietfattendance.py` to parse this new format (and to know which meetings to use which URL path and scraper).

**Comment by lumisota** [comment]
The Datatracker has an endpoint that gives meeting registration data for IETF meetings (from around IETF 72 onwards):
    https://datatracker.ietf.org/api/v1/stats/meetingregistration/

This is exposed by the ietfdata library:
   https://github.com/glasgow-ipl/ietfdata/blob/7d4f4207fe35afa6233aeb787990639b44f6d1ee/ietfdata/datatracker.py#L4036

**Comment by npdoty** [comment]
thank you @lumisota ! I did specifically look at the datatracker's page to try to find this, but didn't see it. Is the recommended way to just look at their Django Python models rather than at the datatracker web page or documentation?

**Comment by lumisota** [comment]
Yes, would do that (links to the models at https://datatracker.ietf.org/api/). Otherwise, the `ietfdata` library provides fairly complete coverage of the API (with a few exceptions).

**Comment by sbenthall** [comment]
oh, that's much better than web scraping the attendance records!

**Comment by npdoty** [comment]
I'm working on an updated notebook that would do some of the graphing/data analysis but will probably use `ietfdata` only. 

It might be that we can remove a whole `.py` file, which I would count as a success. :)

**Comment by sbenthall** [comment]
I agree. Better use of the ietfdata package is a real win.
