### ISSUE TITLE
Make use of Python's email package for EmaiMessage types

### ISSUE THREAD

**Issue by Christovis** [datactive/bigbang#434]
At the moment it seems that we can treat all messages from the current list of data sources as [Python's EmailMessage objects](https://docs.python.org/3/library/email.message.html#email.message.EmailMessage) without loss of important information.
It's Pythonic and let's us take advantage of the existing work/gotchas of other Python people handling email
This object should be made our default for messages from Mailman, W3C, LISTSERV, ... , from which e.g. .mbox can be created.

**Comment by sbenthall** [comment]
That's a good idea.

It looks like the `mailbox` package's `Message` object is a subclass of `email.message` EmailMessage object:
https://docs.python.org/3/library/mailbox.html?highlight=mbox#mailbox.Message

though the documentation may be out of sync? I'm curious what precisely the relationship between these libraries are.

**Comment by Christovis** [comment]
This has been solved with #463
