### ISSUE TITLE
Mailman.py refactor

### ISSUE THREAD

**Issue by Christovis** [datactive/bigbang#435]
At the moment mailman.py contains functions that are either not Gnu-Mailman specific or better placed in archive.py. Furthermore are certain arguments ambiguous. Thus this file should be refactored, and along the way separate mail collecting/provenance stuff and mailman-specific crawling/parsing.

**Comment by sbenthall** [comment]
That sounds good. There is certainly a lot of room for improvement in the code.

I would recommend breaking this down into small incremental changes that can be more easily discussed, approved, and merged.

**Comment by sbenthall** [comment]
Ok, I've been reviewing these files.

I think the changes needed are:

 - move `load_data` and `open_list_archives` to archive.py, and make sure their arguments are consistent with respect to using the _name_ of an archive (possibly reducing a URL, if given, to a name)
 - remove or change the dependency of `collect_from_url` on `open_list_archives`

Am I correct in thinking that the archive.py methods are all general to archives whether they are retrieved using mailman.py, or ,listserv.py, or other ingress-related modules?

**Comment by Christovis** [comment]
"the archive.py methods are all general to archives", this is what we want it to be. Currently however, I have developed the Listserv environment independent from archive.py and I will work on merging them two together. This means merging the class [ListservArchive](https://github.com/datactive/bigbang/blob/e6a7ba464fed84bfb0968fcbcc8079ed2d495727/bigbang/listserv.py#L869) into archive.py.

The modules in `ListservArchive` that mimic `load_data` and `open_list_archives` are:
- [from_url](https://github.com/datactive/bigbang/blob/e6a7ba464fed84bfb0968fcbcc8079ed2d495727/bigbang/listserv.py#L928)
- [from_mbox](https://github.com/datactive/bigbang/blob/e6a7ba464fed84bfb0968fcbcc8079ed2d495727/bigbang/listserv.py#L1070)
- [from_mailing_lists](https://github.com/datactive/bigbang/blob/e6a7ba464fed84bfb0968fcbcc8079ed2d495727/bigbang/listserv.py#L984)
- [from_listserv_directory](https://github.com/datactive/bigbang/blob/e6a7ba464fed84bfb0968fcbcc8079ed2d495727/bigbang/listserv.py#L1035)

**Comment by sbenthall** [comment]
I like this design, @Christovis , and maybe it's a solution to the problem raised by @npdoty here:

https://github.com/datactive/bigbang/pull/500#discussion_r753826294

Maybe it would make sense for `Archive` to be a more abstract class and for it to be subclassed for data sources like `ListservArchive`, `MailmanArchvie`, etc.
