### ISSUE TITLE
charts of the distribution of senders

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#44]
See #43. On the 'Analyzing Mail Senders' notebook, it would be good to have code to generate charts of the distribution of senders.

**Comment by npdoty** [comment]
Has this been subsequently resolved? Here are some notebooks with charts of sender distribution:

https://github.com/datactive/bigbang/blob/master/examples/experimental_notebooks/Analyze%20Senders.ipynb
https://github.com/datactive/bigbang/blob/master/examples/experimental_notebooks/IETF%20Participants.ipynb

And with a little more detail from the IETF hackathon on my own ietf-participation branch:
https://github.com/npdoty/bigbang/blob/ietf-participation/ietf-participation/IETF%20Participants.ipynb

I'm ready to close this issue unless we have something more specific in mind for it.
