### ISSUE TITLE
update URL collections

### ISSUE THREAD

**Issue by nllz** [datactive/bigbang#446]
- [x] add new lists for IETF
- [x] add new lists for ICANN
- [x] add a file with RIPE lists
- [x] add a file with 3GPP lists
- [x] add a file with IEEE lists
- [x] add a file with W3C lists

**Comment by nllz** [comment]
It seems @Christovis made a list of 3GPP lists: https://github.com/datactive/bigbang/blob/main/examples/url_collections/listserv.3GPP.txt
But it is unclear to me as to how lists were selected, because these are not all lists from: https://list.etsi.org/scripts/wa.exe for instance https://list.etsi.org/scripts/wa.exe?A0=3GPP_TSG_SA_WG3_LI is missing

**Comment by Christovis** [comment]
The URL collection for [3GPP](https://github.com/datactive/bigbang/blob/main/examples/url_collections/listserv.3GPP.txt), including  list `3GPP_TSG_SA_WG3_LI`, and [IEEE](https://github.com/datactive/bigbang/blob/main/examples/url_collections/listserv.IEEE.txt) can now completed.

**Comment by nllz** [comment]
Requested new lists from ICANN, since not all the lists are mentioned on their website

**Comment by nllz** [comment]
Closed with https://github.com/datactive/bigbang/pull/568
