### ISSUE TITLE
Create mailinglist mirror collection based on https://github.com/datactive/bigbang/issues/446

### ISSUE THREAD

**Issue by nllz** [datactive/bigbang#447]
- Create a github-lfs with all mailinglist data
- Ideally scraping all lists once per week
- Use this archive a pointer in notebooks? (will minimize downloads + serve the online/binder instance)

**Comment by Christovis** [comment]
the github-lfs as it needs to be payed for starting from 1GB

**Comment by Christovis** [comment]
Using Niels server for now and waiting for Covington advice

**Comment by nllz** [comment]
Awesome! I have a couple of q's: Do you have rsync working with weekly updates as well? Does it work for ICANN, RIPE, IETF, and 3GPP ? Does it get the mailinglists from the GitHub files?
