### ISSUE TITLE
Network analysis on 3GPP mailing lists

### ISSUE THREAD

**Issue by RiccardoNanni** [datactive/bigbang#465]
it seems to me the Jupyter notebook for network analysis does not read the 3GPP file (.mbox), anyone else facing this? I tried both with indicating the name of the folder in the archive name space and with indicating the name of the file (after moving it to the archive folder). I also tried changing the file extension to '.mail' and '.csv', but wouldn't work anyway. The notebook still says file not found.

Anyone has any hint on this?
Thanks!

**Comment by Christovis** [comment]
Yes, the notebookes/code-the-notebooks-depend-on need to be imrproved.
Essentially, what that particular [notebook](https://github.com/datactive/bigbang/blob/main/examples/network_analysis/InteractionNetwork.ipynb) needs is a pandas.DataFrame, which you can create for Listserv 16.5 mailing lists as ListservList.from_mbox(name=... , filepath=...).to_pandas_dataframe() (for details see [here](https://github.com/datactive/bigbang/blob/314a47b88379394765e9dbfd324584efa7476738/bigbang/listserv.py#L517) ).

However, I can already tell you that there is not much to see in the particular network analysis done in the notebook, as the senders and receivers are for some reason always the same (which you can also see from the website, and I don't now why the 3GPP mailinglist is handled that way).

**Comment by RiccardoNanni** [comment]
Thank you @Christovis!
I'll try it.

**Comment by Christovis** [comment]
Assume this has been resolved by now
