### ISSUE TITLE
pypi package for bigbang

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#473]
@maxigas

**Comment by maxigas** [comment]
We need to sort out a namespace issue where there is another project called BigBang on pypi. The project does not seem to be very active and @nllz contacts the maintainer to ask whether they need that old version of the package in the repository. If not, then we can use the BigBang name, if yes, then we need to (perhaps slightly) modify the project name.

**Comment by maxigas** [comment]
The immediate utility of this would be to make BigBang work in environments like Google Collab where code cannot be installed from source, but only from pypi packages.

**Comment by nllz** [comment]
Email sent

**Comment by nllz** [comment]
https://github.com/Fabfm4/bigbang-python/issues/1

**Comment by sbenthall** [comment]
It looks like we settled on the name of the package, but nobody ever bothered shipping this to PyPi before closing this ticket.

@MridulS @nllz
