### ISSUE TITLE
Add nationalities + 3GPP countries to categories csv

### ISSUE THREAD

**Issue by nllz** [datactive/bigbang#492]
@nllz will add nationalities and categories/sectors based on the main actors in the 3GPP that @Christovis will provide. 

https://github.com/datactive/bigbang/blob/main/examples/organizations/organization_categories.csv

**Comment by Christovis** [comment]
This is part of #371

**Comment by Christovis** [comment]
We have added the information in [here](https://github.com/datactive/bigbang/blob/main/examples/organizations/organization_categories.csv). It will be updated soon again and we are working on a method to automatise what has been done by hand so far.
