### ISSUE TITLE
Mastodon account for this project

### ISSUE THREAD

**Issue by Lukas2112** [datactive/bigbang#496]
Would a Mastodon account for this project be possible?

**Comment by npdoty** [comment]
It sounds like a fun idea to me, but I'm not sure whether we would use it much. It could make sense to use social media for announcements of new releases, events/hackathons, or sharing of uses of bigbang or related work. But I suspect that we wouldn't have a lot of followers and having someone in charge of updates might be more confusing than just having individuals post to their own accounts when they see something relevant.

**Comment by Christovis** [comment]
As this suggestion is not relevant for the development of Bigbang right now, I will close this issue.
