### ISSUE TITLE
w3c scraping hangs

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#538]
Collecting w3c data like this:

```
$ python bin/collect_mail.py -u http://lists.w3.org/Archives/Public/public-privacy/
```

Hangs with no feedback to the user.

This is problematic because some notebooks in the examples/ directory depend on this data, like:

https://github.com/datactive/bigbang/blob/main/examples/experimental_notebooks/Analyze%20Senders.ipynb

**Comment by Christovis** [comment]
If @npdoty is ok with the refactored w3c code in PR #534 I can take care of this issue.

**Comment by Christovis** [comment]
PR #534 is merged now which means that W3C obtained a make over which solves this issue. You can check the ingress tests and docstring for information on how to use it to ingress the mailing lists.
Notebooks will be affected by this change and might fail. But this can be addressed in a different issue.
