### ISSUE TITLE
w3C mailman ingress fails due to HTML change

### ISSUE THREAD

**Issue by laurenmarietta** [datactive/bigbang#600]
I was trying to run `collect-mail` on the provided [list of W3C mailing lists](https://github.com/datactive/bigbang/blob/62be195b791e84e7a26ff3f761093ada642f21bb/examples/url_collections/W3C.txt) and was confused as to why almost all of the URLs weren't returning files.

It seems that, sometime between 2020 and now, W3C has subtly changed the HTML for its mailing list archives. From this [Internet Archive page](https://web.archive.org/web/20211201111020/https://lists.w3.org/Archives/Public/public-comments-wai-age/2017Feb/), they used to be listed in a `div` with `class=messages-list`, but [today's version of the same URL](https://lists.w3.org/Archives/Public/public-comments-wai-age/2017Feb/) lists them within a `main` tag under `class=messages-list`. Because the [`W3CMailList` class explicitly looks for email records under `div.messages-list`](https://github.com/datactive/bigbang/blob/62be195b791e84e7a26ff3f761093ada642f21bb/bigbang/ingress/w3c.py#L244C49-L244C49), the scans are coming up empty.

Not sure if it's as simple a fix as replacing `div` with `main` or if there are more complicated things to consider here!

**Comment by sbenthall** [comment]
I haven't worked much with the W3C ingress scripts before.

I was able to confirm that the change you mention make the W3C collection work better, and have committed it:
[6a0ec35](https://github.com/datactive/bigbang/commit/6a0ec35731990af0d7d84cf845a2db339def9cd7)

I've also updated the docs to fix the example W3C ingest script:
https://github.com/datactive/bigbang/blob/main/docs/datasets/mailinglists.rst

However, the W3C records that I've been able to ingest are missing the email body, and I haven't yet figured out how to retrieve them.

Can you please confirm that you can get past this issue with the `main` branch, close this issue, and file any other problems or requests in separate issues?

Thanks for kicking the tires.

**Comment by sbenthall** [comment]
Actually, confirmed both that it works better (passing more tests) and that the missing body issue is new.
