### ISSUE TITLE
Reconsider bigbang LICENSE

### ISSUE THREAD

**Issue by davelester** [datactive/bigbang#74]
I noticed that bigbang is currently licensed under the GNU General Public License v2; would the current contributors consider relicensing under a more permissive license like BSD or MIT? Some related projects and dependencies like scipy are already licensed under BSD.

**Comment by sbenthall** [comment]
I've considered this carefully, and concluded that based on the project's goals, it would be better to start with the GPL license for now.

https://github.com/datactive/bigbang/wiki/Why-GPL-for-BigBang%3F

If developers or an organization would like this to change, I strongly encourage them to work towards that change using the community Governance mechanisms.

https://github.com/datactive/bigbang/wiki/Governance
